language: ruby
dist: trusty
sudo: required
bundler_args: --without benchmarks tools
script:
  - bundle exec rake spec
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.2.7
  - 2.3.3
  - 2.4.1
  - jruby-9.1.10.0
env:
  global:
    - COVERAGE=true
    - JRUBY_OPTS='--dev -J-Xmx1024M'
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
