language: ruby
dist: trusty
sudo: required
bundler_args: --without benchmarks tools
script:
  - bundle exec rake spec
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.4.5
  - 2.5.5
  - 2.6.2
  - jruby-9.2.6.0
  - truffleruby
env:
  global:
    - COVERAGE=true
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: truffleruby
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
